spring:
  profiles:
    active: dev
  application:
    name: eureka-provider  #虚拟主机名，ribbon调用时，需要使用到
server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true #配合下面的，必须要加
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}} #eureka注册显示的主机名
---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/test
    username: root
    password: yang156122
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
