server:
  port: 7010
user:
  httpAddress: http://eureka-provider/getUser/  #使用虚拟主机名

spring:
  application:
    name: eureka-client-ribbon
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka